# Building the final models
---
### Models to build:
- Ridge (the best model)
- LGBMRegressor

In [9]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import QuantileTransformer
from sklearn.compose import ColumnTransformer

from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.linear_model import Ridge
from lightgbm import LGBMRegressor

import matplotlib.pyplot as plt
import plotly.graph_objects as go

from sklearn.base import BaseEstimator, RegressorMixin, clone
import joblib

In [2]:
def regression_metrics(y_true, y_pred):
    rmse = round(np.sqrt(mean_squared_error(y_true, y_pred)), 3)
    mae = round(mean_absolute_error(y_true, y_pred), 3)
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    denom = np.sum(np.abs(y_true))
    wape = np.sum(np.abs(y_true - y_pred)) / denom
    return {'rmse':rmse, 'mae':mae, 'wape':round(wape, 3)}

In [3]:
df = pd.read_csv("dados/CompactedData.csv")
df["Date"] = pd.to_datetime(df.Date)
df.set_index('Date', inplace=True)
df.head(3)

,UNETOT_PT_ea-md,UNEO25_PT_ea-md,UNEU25_PT_ea-md,REER42_PT_ea-md,LTIRT_PT_ea-md,IPMN_PT_ea-md,IPCAG_PT_ea-md,IPCOG_PT_ea-md,IPDCOG_PT_ea-md,IPNDCOG_PT_ea-md,...,OILPRICEx_fred-md,CUSR0000SAC_fred-md,PCEPI_fred-md,S&P 500_fred-md,epu_pt_epu,unemployment_up_15_unemployment,exchange_exchange,PPIPT_ppi,inflation_target,OILPRICEx_fred-md_Eur
Date,,,,,,,,,,,,,,,,,,,,,
2000-01-01,5.6,4.4,12.7,96.14621,5.81,123.5,191.3,118.0,129.6,116.5,...,27.18,146.7,72.961,1425.59,107.096201,5.6,0.9791,21.5,2.1,27.760188
2000-02-01,5.4,4.1,13.0,95.12462,5.78,122.7,177.4,119.8,131.1,118.2,...,29.35,147.6,73.191,1388.87,105.539878,5.4,0.9714,21.9,1.8,30.214124
2000-03-01,5.3,4.0,12.4,94.49293,5.61,116.5,164.6,116.5,124.8,115.3,...,29.89,149.1,73.505,1442.21,68.844150,5.3,0.9553,21.2,1.5,31.288600

In [4]:
def outliers(X, level=0):
    """
        - X: variável onde se verifica os outliers
        - level: default 0 - outliers não severos; 1 outliers severos
    """

    assert level in (0, 1), "Level invalido - valores aceites (0, 1)"

    out_level = (1.5, 3)
    Q1 = X.quantile(.25)
    Q3 = X.quantile(.75)
    IQR = Q3 - Q1

    left = Q1 - out_level[level] * IQR
    right = Q3 + out_level[level] * IQR

    return (left, right)

In [5]:
vars_model = [
    'PCEPI_fred-md', 'HICPOV_PT_ea-md', 'HICPNEF_PT_ea-md',
    'HICPNG_PT_ea-md', 'PPIPT_ppi', 'HICPSV_PT_ea-md',
    'CCI_PT_ea-md', 'EXPGS_PT_ea-qd', 'epu_pt_epu'
]

data = df[vars_model + ['inflation_target', ]].copy()
data.head(3)

,PCEPI_fred-md,HICPOV_PT_ea-md,HICPNEF_PT_ea-md,HICPNG_PT_ea-md,PPIPT_ppi,HICPSV_PT_ea-md,CCI_PT_ea-md,EXPGS_PT_ea-qd,epu_pt_epu,inflation_target
Date,,,,,,,,,,
2000-01-01,72.961,57.431740,62.712032,42.419421,21.5,49.779425,102.3880,NaN,107.096201,2.1
2000-02-01,73.191,57.437413,62.746704,42.538342,21.9,49.867652,102.2470,NaN,105.539878,1.8
2000-03-01,73.505,57.466046,62.816039,42.544582,21.2,49.933135,101.9521,10151.5,68.844150,1.5

In [9]:
variables = dict()

for col in data.columns:
    left, right = outliers(data[col])
    variables[col] = data.loc[(data[col] < left) | (data[col] > right)].shape[0]

pd.Series(variables).sort_values(ascending=False)

PPIPT_ppi           25
inflation_target    12
epu_pt_epu           5
HICPNEF_PT_ea-md     1
CCI_PT_ea-md         1
PCEPI_fred-md        0
HICPOV_PT_ea-md      0
HICPNG_PT_ea-md      0
HICPSV_PT_ea-md      0
EXPGS_PT_ea-qd       0
dtype: int64

In [10]:
out_variables = pd.Series(variables).sort_values(ascending=False)

cols_quantile = [col for col in out_variables[out_variables > 0].index if col != 'inflation_target']
cols_standard = out_variables[out_variables == 0].index.tolist()

# Define os transformers
preprocessor = ColumnTransformer(
    transformers=[
        ('std', StandardScaler(), cols_standard),
        ('quantile', QuantileTransformer(n_quantiles=min(100, data.shape[0]), 
                                         output_distribution='normal',
                                         random_state=322
                                        ), cols_quantile)
    ],
    remainder='passthrough'  # mantém outras colunas sem alteração
)

transformer = preprocessor.fit(data)

In [11]:
cols_out = cols_standard + cols_quantile + [col for col in data.columns if col not in cols_standard + cols_quantile]

df_transformed = pd.DataFrame(transformer.transform(data), columns=cols_out)
df_transformed.index = data.index
df_transformed.head()

,PCEPI_fred-md,HICPOV_PT_ea-md,HICPNG_PT_ea-md,HICPSV_PT_ea-md,EXPGS_PT_ea-qd,PPIPT_ppi,epu_pt_epu,HICPNEF_PT_ea-md,CCI_PT_ea-md,inflation_target
Date,,,,,,,,,,
2000-01-01,-1.559557,-1.966458,-1.832207,-1.938298,NaN,2.152479,0.430727,-5.199338,5.199338,2.1
2000-02-01,-1.543606,-1.965909,-1.825420,-1.931111,NaN,2.322575,0.370961,-2.842667,2.332470,1.8
2000-03-01,-1.521828,-1.963137,-1.825064,-1.925777,-1.369928,2.056568,-1.159841,-2.472415,1.640603,1.5
2000-04-01,-1.526059,-1.938305,-1.733034,-1.920588,NaN,1.841348,-1.111979,-2.364643,1.378119,2.1
2000-05-01,-1.521828,-1.937183,-1.743743,-1.907701,NaN,1.747999,-0.725246,-2.280374,1.221062,2.5

In [12]:
# guardar no disco
joblib.dump(transformer, "models/standardize_features.pkl")

['models/standardize_features.pkl']

In [13]:
cols_out

['PCEPI_fred-md',
 'HICPOV_PT_ea-md',
 'HICPNG_PT_ea-md',
 'HICPSV_PT_ea-md',
 'EXPGS_PT_ea-qd',
 'PPIPT_ppi',
 'epu_pt_epu',
 'HICPNEF_PT_ea-md',
 'CCI_PT_ea-md',
 'inflation_target']

In [6]:
from FinalPipeline import *
from FinalPipeline import prepare_dataset as DataPipeline

In [8]:
RANDOM_STATE = 322

data_treated = DataPipeline(data, treat_outliers=True, create_lags=True)['prepared_data'].dropna()
X = data_treated.drop('inflation_target', axis=1)
y = data_treated['inflation_target']

clf1 = Ridge(random_state=RANDOM_STATE)
clf1.fit(X, y)

Ridge(random_state=322)

HICPOV_PT_ea-md_lag_12
HICPNEF_PT_ea-md_lag_12
HICPSV_PT_ea-md_lag_12 *
HICPNG_PT_ea-md_lag_12
epu_pt_epu_lag_6
PPIPT_ppi_lag_1

inflation_target_lag_1

In [43]:
class InflationModel(BaseEstimator, RegressorMixin):

    def __init__(
        self,
        model=None,
        treat_outliers=True,
        create_lags=True,
    ):
        self.model = model if model is not None else Ridge()

        self.target_col = 'inflation_target'
        self.target_lag_col = 'inflation_target_lag_1'
        
        self.treat_outliers = treat_outliers
        self.create_lags = create_lags

    def fit(self, data, y=None):
        
        self.train_data_ = data.copy()

        # Preparação dos dados
        prepared = DataPipeline(
            data,
            treat_outliers=self.treat_outliers,
            create_lags=self.create_lags
        )['prepared_data'].dropna()

        # Separar features e target
        X = prepared.drop([self.target_col, 'epu_pt_epu', 'HICPSV_PT_ea-md'], axis=1)
        y = prepared[self.target_col]

        # Clone para evitar side effects
        self.model_ = clone(self.model)

        # Treino
        self.model_.fit(X, y)

        # Guardar colunas utilizadas
        self.feature_names_ = X.columns

        return self

    def predict(self, data):

        # Aplicar exatamente o mesmo pipeline
        prepared = DataPipeline(
            data,
            treat_outliers=self.treat_outliers,
            create_lags=self.create_lags
        )['prepared_data']

        # Garantir mesmas colunas do treino
        X = prepared[self.feature_names_]

        return self.model_.predict(X)

    def forecast(self, future_data):

        history = self.train_data_.copy()

        forecasts = list()

        for idx in future_data.index:
            history = pd.concat([
                history,
                future_data.loc[[idx]]
            ])

            prepared = DataPipeline(
                history,
                treat_outliers=self.treat_outliers,
                create_lags=self.create_lags
            )['prepared_data']

            current_row = prepared.iloc[[-1]]

            X = current_row[self.feature_names_]

            # Forecast
            pred = self.model_.predict(X)[0]

            forecasts.append(pred)

            history.loc[idx, self.target_col] = pred

        return pd.Series(
            forecasts,
            index=future_data.index,
            name='forecast'
        )

    @property
    def explainability_(self):
    
        if hasattr(self.model_, 'coef_'):
    
            return pd.Series(
                self.model_.coef_,
                index=self.feature_names_
            )
    
        elif hasattr(self.model_, 'feature_importances_'):
    
            return pd.Series(
                self.model_.feature_importances_,
                index=self.feature_names_
            ).sort_values(ascending=False)
    
        else:
    
            raise AttributeError(
                'Modelo não suporta explicabilidade.'
            )

In [44]:
model_ridge = InflationModel(
    model=Ridge(random_state=RANDOM_STATE),
    treat_outliers=True,
    create_lags=True
)

model_ridge.fit(data)

# preds = model_ridge.predict(data_test)

InflationModel(model=Ridge(random_state=322))

In [46]:
model_ridge.explainability_

PCEPI_fred-md              0.675938
HICPOV_PT_ea-md            0.871899
HICPNG_PT_ea-md            0.711846
EXPGS_PT_ea-qd             0.167729
PPIPT_ppi                  0.082159
HICPNEF_PT_ea-md           0.255787
CCI_PT_ea-md              -0.056660
HICPOV_PT_ea-md_lag_12    -1.304798
HICPNG_PT_ea-md_lag_12    -0.839709
HICPSV_PT_ea-md_lag_12    -0.450203
PPIPT_ppi_lag_1           -0.138163
epu_pt_epu_lag_6          -0.019195
HICPNEF_PT_ea-md_lag_12   -0.159542
inflation_target_lag_1     0.759220
dtype: float64

In [32]:
future_df = pd.DataFrame({
    'PCEPI_fred-md':        list(range(100, 124)),
    'HICPOV_PT_ea-md':      list(range(200, 224)),
    'HICPNEF_PT_ea-md':     list(range(300, 324)),
    'HICPNG_PT_ea-md':      list(range(400, 424)),
    'PPIPT_ppi':            list(range(500, 524)),
    'HICPSV_PT_ea-md':      list(range(600, 624)),
    'CCI_PT_ea-md':         list(range(700, 724)),
    'EXPGS_PT_ea-qd':       list(range(800, 824)),
    'epu_pt_epu':           list(range(900, 924))
})

future_df['inflation_target'] = 0

last_3 = future_df.tail(3)

last_3.index = pd.date_range(
    start=data.index[-1] + pd.offsets.MonthBegin(),
    periods=len(last_3),
    freq="MS"
)

last_3.head()

,PCEPI_fred-md,HICPOV_PT_ea-md,HICPNEF_PT_ea-md,HICPNG_PT_ea-md,PPIPT_ppi,HICPSV_PT_ea-md,CCI_PT_ea-md,EXPGS_PT_ea-qd,epu_pt_epu,inflation_target
2025-11-01,121,221,321,421,521,621,721,821,921,0
2025-12-01,122,222,322,422,522,622,722,822,922,0
2026-01-01,123,223,323,423,523,623,723,823,923,0

In [33]:
model_ridge.forecast(last_3)

2025-11-01    25.203392
2025-12-01    41.708942
2026-01-01    54.287387
Freq: MS, Name: forecast, dtype: float64

In [34]:
joblib.dump(model_ridge, 'models/ridge_model.pkl')

['models/ridge_model.pkl']

In [35]:
model_lgbm = InflationModel(
    model=LGBMRegressor(        
        random_state=RANDOM_STATE,
        verbose=-1,
    ),
    treat_outliers=True,
    create_lags=True
)

model_lgbm.fit(data)

InflationModel(model=LGBMRegressor(random_state=322, verbose=-1))

In [36]:
model_lgbm.explainability_

inflation_target_lag_1     168
CCI_PT_ea-md               138
PPIPT_ppi                  133
PPIPT_ppi_lag_1            126
HICPNG_PT_ea-md            115
epu_pt_epu_lag_6           111
HICPNG_PT_ea-md_lag_12      57
HICPNEF_PT_ea-md            45
HICPOV_PT_ea-md             43
HICPOV_PT_ea-md_lag_12      34
PCEPI_fred-md               32
EXPGS_PT_ea-qd              30
HICPNEF_PT_ea-md_lag_12     23
HICPSV_PT_ea-md_lag_12      20
dtype: int32

In [37]:
model_lgbm.forecast(last_3)

2025-11-01    3.323830
2025-12-01    5.256255
2026-01-01    7.788701
Freq: MS, Name: forecast, dtype: float64

In [39]:
joblib.dump(model_lgbm, 'models/lgbm_model.pkl')

['models/lgbm_model.pkl']