In [2]:
import pandas as pd
import numpy as np

In [3]:
df_target = pd.read_csv("dados/target.csv", encoding='"latin1"', sep=';')
df_fred_md = pd.read_csv("dados/2026-01-MD.csv")
df_ppi = pd.read_csv("dados/PPI_PT.csv")

df_epu = pd.read_excel("dados/epuptindex_data.xlsx")
df_unemployment = pd.read_excel("dados/monthly unemployment rates.xlsx", skiprows=7)

df_ea_md = pd.read_excel("dados/EA-MD-QD-2026-02/data_TR3/monthly-PT.xlsx")
df_ea_qd = pd.read_excel("dados/EA-MD-QD-2026-02/data_TR3/quarter-PT.xlsx")

In [4]:
df_exchange = pd.read_csv("dados/exchange_rate.csv", encoding='"latin1"', sep=';')
df_exchange.head()

,# Série,Designação da série (PT),Métrica,Unidade de Medida,Período de referência,Valor,Estado
0,12532123,Dólar dos EUA (USD) - fim de mês,Valor em fim do período,Divisa,1999-01-31,1.1384,NaN
1,12532123,Dólar dos EUA (USD) - fim de mês,Valor em fim do período,Divisa,1999-02-28,1.1018,NaN
2,12532123,Dólar dos EUA (USD) - fim de mês,Valor em fim do período,Divisa,1999-03-31,1.0742,NaN
3,12532123,Dólar dos EUA (USD) - fim de mês,Valor em fim do período,Divisa,1999-04-30,1.0597,NaN
4,12532123,Dólar dos EUA (USD) - fim de mês,Valor em fim do período,Divisa,1999-05-31,1.0456,NaN

In [4]:
df_exchange.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 326 entries, 0 to 325
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   # Série                   326 non-null    int64
 1   Designação da série (PT)  326 non-null    object
 2   Métrica                   326 non-null    object
 3   Unidade de Medida         326 non-null    object
 4   Período de referência     326 non-null    object
 5   Valor                     326 non-null    float64
 6   Estado                    0 non-null      float64
dtypes: float64(2), int64(1), object(4)
memory usage: 18.0+ KB

In [5]:
cat_cols = df_exchange.select_dtypes('O').columns
for col in cat_cols:
    print("-" * 40)
    print(f"Variável: {col}")
    print("-" * 40)
    print(df_exchange[col].value_counts())

----------------------------------------
Variável: Designação da série (PT)
----------------------------------------
Designação da série (PT)
Dólar dos EUA (USD) - fim de mês    326
Name: count, dtype: int64
----------------------------------------
Variável: Métrica
----------------------------------------
Métrica
Valor em fim do período    326
Name: count, dtype: int64
----------------------------------------
Variável: Unidade de Medida
----------------------------------------
Unidade de Medida
Divisa    326
Name: count, dtype: int64
----------------------------------------
Variável: Período de referência
----------------------------------------
Período de referência
1999-01-31    1
2016-01-31    1
2017-07-31    1
2017-06-30    1
2017-05-31    1
             ..
2007-12-31    1
2007-11-30    1
2007-10-31    1
2007-09-30    1
2026-02-28    1
Name: count, Length: 326, dtype: int64

## Target Dataset

In [6]:
df_target.head()

,# Série,Designação da série (PT),Métrica,Unidade de Medida,Período de referência,Valor,Estado
0,5721524,IPC total-taxa de variação homóloga,Taxa de variação homóloga,Percentagem,31/01/1949,4.4,NaN
1,5721524,IPC total-taxa de variação homóloga,Taxa de variação homóloga,Percentagem,28/02/1949,4.2,NaN
2,5721524,IPC total-taxa de variação homóloga,Taxa de variação homóloga,Percentagem,31/03/1949,4.8,NaN
3,5721524,IPC total-taxa de variação homóloga,Taxa de variação homóloga,Percentagem,30/04/1949,3.8,NaN
4,5721524,IPC total-taxa de variação homóloga,Taxa de variação homóloga,Percentagem,31/05/1949,4.5,NaN

In [7]:
df_target.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 924 entries, 0 to 923
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   # Série                   924 non-null    int64
 1   Designação da série (PT)  924 non-null    object
 2   Métrica                   924 non-null    object
 3   Unidade de Medida         924 non-null    object
 4   Período de referência     924 non-null    object
 5   Valor                     924 non-null    float64
 6   Estado                    0 non-null      float64
dtypes: float64(2), int64(1), object(4)
memory usage: 50.7+ KB

In [8]:
cat_cols = df_target.select_dtypes('O').columns
for col in cat_cols:
    print("-" * 40)
    print(f"Variável: {col}")
    print("-" * 40)
    print(df_target[col].value_counts())

----------------------------------------
Variável: Designação da série (PT)
----------------------------------------
Designação da série (PT)
IPC total-taxa de variação homóloga    924
Name: count, dtype: int64
----------------------------------------
Variável: Métrica
----------------------------------------
Métrica
Taxa de variação homóloga    924
Name: count, dtype: int64
----------------------------------------
Variável: Unidade de Medida
----------------------------------------
Unidade de Medida
Percentagem    924
Name: count, dtype: int64
----------------------------------------
Variável: Período de referência
----------------------------------------
Período de referência
31/01/1949    1
31/08/1999    1
31/10/1999    1
30/11/1999    1
31/12/1999    1
             ..
31/12/1974    1
31/01/1975    1
28/02/1975    1
31/03/1975    1
31/12/2025    1
Name: count, Length: 924, dtype: int64

## Other datasets

In [9]:
# Eliminar a linha 0
df_fred_md.head()

,sasdate,RPI,W875RX1,DPCERA3M086SBEA,CMRMTSPLx,RETAILx,INDPRO,IPFPNSS,IPFINAL,IPCONGD,...,DNDGRG3M086SBEA,DSERRG3M086SBEA,CES0600000008,CES2000000008,CES3000000008,UMCSENTx,DTCOLNVHFNM,DTCTHFNM,INVEST,VIXCLSx
0,Transform:,5.000,5.0,5.000,5.0000,5.00000,5.0000,5.0000,5.0000,5.0000,...,6.000,6.000,6.00,6.00,6.00,2.0,6.0,6.0,6.0000,1.0
1,1/1/1959,2583.560,2426.0,15.188,276676.8154,17689.23968,21.9998,23.6312,22.5507,32.1377,...,18.294,10.152,2.13,2.45,2.04,NaN,6476.0,12298.0,84.2043,NaN
2,2/1/1959,2593.596,2434.8,15.346,278713.9773,17819.01912,22.4306,23.9501,22.7461,32.3734,...,18.302,10.167,2.14,2.46,2.05,NaN,6476.0,12298.0,83.5280,NaN
3,3/1/1959,2610.396,2452.7,15.491,277775.2539,17967.91336,22.7538,24.0951,22.8577,32.3734,...,18.289,10.185,2.15,2.45,2.07,NaN,6508.0,12349.0,81.6405,NaN
4,4/1/1959,2627.446,2470.0,15.435,283362.7075,17978.97983,23.2384,24.4431,23.1926,32.8841,...,18.300,10.221,2.16,2.47,2.08,NaN,6620.0,12484.0,81.8099,NaN

In [10]:
df_fred_md.tail()

,sasdate,RPI,W875RX1,DPCERA3M086SBEA,CMRMTSPLx,RETAILx,INDPRO,IPFPNSS,IPFINAL,IPCONGD,...,DNDGRG3M086SBEA,DSERRG3M086SBEA,CES0600000008,CES2000000008,CES3000000008,UMCSENTx,DTCOLNVHFNM,DTCTHFNM,INVEST,VIXCLSx
800,8/1/2025,20582.726,16638.6,124.869,1562681.0,731700.0,101.5867,97.7621,97.7555,98.3075,...,120.335,133.220,32.58,37.49,29.08,58.2,547634.28,937137.80,5628.6726,15.7545
801,9/1/2025,20601.264,16651.2,125.007,1551628.0,732192.0,101.7779,97.9941,97.9522,98.2327,...,121.218,133.452,32.71,37.61,29.21,55.1,542484.79,935729.08,5651.1169,15.6325
802,10/1/2025,20592.481,16646.0,125.390,1554989.0,731412.0,101.5163,97.6578,97.5438,97.5637,...,120.897,133.832,32.81,37.69,29.34,53.6,540148.30,934485.63,5661.0021,18.0058
803,11/1/2025,20612.309,16667.0,125.769,NaN,735904.0,101.9528,98.0290,97.9867,98.1242,...,121.119,134.138,32.98,37.88,29.49,51.0,538661.37,933603.64,5658.5233,19.3448
804,12/1/2025,NaN,NaN,NaN,NaN,NaN,102.3250,98.5218,98.7412,98.8497,...,NaN,NaN,33.07,38.08,29.51,52.9,NaN,NaN,5622.7521,15.3137

In [11]:
# Eliminar as duas últimas colunas
df_epu.head()

,Unnamed: 0,epu_pt,Unnamed: 2,Cite it as follows:
0,1998m1,134.655810,NaN,"Morão, H. (2024). An economic policy uncertain..."
1,1998m2,91.742596,NaN,Regular updates:
2,1998m3,92.135717,NaN,https://github.com/hmorao95/epu_portugal
3,1998m4,112.026194,NaN,NaN
4,1998m5,125.879406,NaN,NaN

In [12]:
# Eliminar a última coluna
df_unemployment.head()

  Time period  Value Unnamed: 2
0    1983-Jan    8.1        NaN
1    1983-Feb    8.1        NaN
2    1983-Mar    8.3        NaN
3    1983-Apr    8.5        NaN
4    1983-May    8.8        NaN

In [13]:
df_ea_md.head()

,Time,UNETOT_PT,UNEO25_PT,UNEU25_PT,REER42_PT,LTIRT_PT,IPMN_PT,IPCAG_PT,IPCOG_PT,IPDCOG_PT,...,HICPNG_PT,ICONFIX_PT,CCONFIX_PT,ESENTIX_PT,KCONFIX_PT,RTCONFIX_PT,SCONFIX_PT,BCI_PT,CCI_PT,SHIX_PT
0,2000-01-01,5.6,4.4,12.7,96.14621,5.81,123.5,191.3,118.0,129.6,...,42.419421,7.3,-2.4,113.9,-15.8,9.4,10.3,102.2262,102.3880,110.4053
1,2000-02-01,5.4,4.1,13.0,95.12462,5.78,122.7,177.4,119.8,131.1,...,42.538342,8.9,-3.0,116.7,-5.6,11.0,14.2,102.5146,102.2470,124.9385
2,2000-03-01,5.3,4.0,12.4,94.49293,5.61,116.5,164.6,116.5,124.8,...,42.544582,7.7,-3.2,116.2,-0.1,11.7,11.9,102.6476,101.9521,128.3406
3,2000-04-01,5.2,3.9,12.8,94.90064,5.52,115.5,159.3,118.0,125.3,...,44.157190,8.8,-9.2,114.1,-13.5,6.1,13.2,102.7988,101.5175,115.6546
4,2000-05-01,5.3,4.0,13.1,94.96760,5.68,120.8,171.0,121.0,127.9,...,43.969543,10.1,-8.0,113.3,-3.7,1.5,6.0,102.8972,101.2843,112.0247

In [14]:
df_ea_qd.head()

,Time,GDP_PT,EXPGS_PT,IMPGS_PT,GFCE_PT,HFCE_PT,CONSD_PT,GCF_PT,GFCF_PT,GFACON_PT,...,HHLB.LLN_PT,ULCIN_PT,ULCMQ_PT,ULCMN_PT,ULCCON_PT,ULCRT_PT,ULCFC_PT,ULCRE_PT,ULCPR_PT,DFGDP_PT
0,2000-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000-02-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000-03-01,43450.6,10151.5,13257.6,7387.6,28123.5,3524.1,10981.3,11097.5,7270.5,...,59309.7,64.8,NaN,NaN,NaN,72.2,NaN,NaN,NaN,72.43
3,2000-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_ppi.head()

         Date  PPIPT
0  2000-01-01   21.5
1  2000-02-01   21.9
2  2000-03-01   21.2
3  2000-04-01   20.0
4  2000-05-01   17.9

In [6]:
df_ppi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 315 entries, 0 to 314
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    315 non-null    object
 1   PPIPT   315 non-null    float64
dtypes: float64(1), object(1)
memory usage: 5.1+ KB

### Como estão as datas definidas?
- **target**: `Período de referência` - DD/MM/AAAA
- **fred-md**: `sasdate` - M/D/AAAA
- **epu**: `Unnamed: 0` - AAAAmM
- **unemployment**: `Time period` - AAAA-month_short_name
- **ea-md & ea-qd**: `Time` - AAAA-MM-DD
- **ppi**: `Date` - AAAA-MM-DD

---
### Principais problemas das Bases de Dados
- **target:** sem problemas, em princípio, só precisamos de duas variáveis;
- **fred-md:** eliminar a linha 0 e só precisamos de 8 variáveis da base de dados;
- **epu:** eliminar as duas últimas colunas e mudar o nome da primeira para Date ou algo assim;
- **unemployment:** eliminar a última coluna;
- **ea-md & ea-qd:** sem stress para a primeira, a segunda vai precisar que apliquemos interpolação.

In [7]:
df_exchange = df_exchange[['Período de referência', 'Valor']]

In [8]:
df_target = df_target[['Período de referência', 'Valor']]

cols_fred_global = [
    'sasdate', 'INDPRO', 'IPFINAL', 'IPCONGD',
    'AWOTMAN', 'AWHMAN', 'FEDFUNDS', 'GS1', 'GS5',
    'GS10', 'AAA', 'BAA', 'OILPRICEx', 'CUSR0000SAC',
    'PCEPI', 'S&P 500'
]
df_fred_md = df_fred_md.iloc[1:].reset_index(drop=True)[cols_fred_global]

df_epu.drop(df_epu.columns[-2:], axis=1, inplace=True)

df_unemployment.drop(df_unemployment.columns[-1], axis=1, inplace=True)

# df_ea_md # Está good
# df_ea_qd # Interpolação

In [9]:
default_date = 'Date'

df_target.rename({'Período de referência': default_date}, axis=1, inplace=True)
df_fred_md.rename({'sasdate': default_date}, axis=1, inplace=True)
df_epu.rename({'Unnamed: 0': default_date}, axis=1, inplace=True)
df_unemployment.rename({'Time period': default_date}, axis=1, inplace=True)

df_ea_md.rename({'Time': default_date}, axis=1, inplace=True)
df_ea_qd.rename({'Time': default_date}, axis=1, inplace=True)

In [10]:
df_exchange.rename({'Período de referência': default_date}, axis=1, inplace=True)

In [11]:
df_unemployment['Date'].str.split('-').str.len().value_counts()

Date
2.0    516
1.0      1
Name: count, dtype: int64

In [12]:
df_unemployment.loc[df_unemployment['Date'].str.split('-').str.len() == 1]

                      Date  Value
517  © Terms & conditions     NaN

In [13]:
df_unemployment.dropna(axis=0, inplace=True)
df_unemployment.reset_index(drop=True, inplace=True)

In [14]:
df_unemployment['Date'].str.split('-').str.len().value_counts()

Date
2    516
Name: count, dtype: int64

In [15]:
df_unemployment['Date'].str.split('-').str[-1].value_counts()

Date
Jan    43
Feb    43
Mar    43
Apr    43
May    43
Jun    43
Jul    43
Aug    43
Sep    43
Oct    43
Nov    43
Dec    43
Name: count, dtype: int64

In [16]:
df_target['Date'] = pd.to_datetime(
    df_target['Date'],
    dayfirst=True
)

df_fred_md['Date'] = pd.to_datetime(
    df_fred_md['Date']
)

df_ea_md['Date'] = pd.to_datetime(
    df_ea_md['Date']
)

df_ea_qd['Date'] = pd.to_datetime(
    df_ea_qd['Date']
)

# New dataset
df_ppi['Date'] = pd.to_datetime(
    df_ppi['Date']
)

df_epu['Date'] = pd.to_datetime(
    df_epu['Date'].str.replace('m', '/'),
    format='%Y/%m'
)

df_unemployment['Date'] = pd.to_datetime(
    df_unemployment['Date'],
    format='%Y-%b'
)

In [17]:
df_exchange['Date'] = pd.to_datetime(
    df_exchange['Date'],
    format='%Y-%m-%d'
)

### Coisas importantes a verificar
- Para cada uma das bases de dados os valores correspondem ao que foi calculado no último dia do mês ou no primeiro do mês seguinte?
    - **target:** Último dia do mês (ponderando colocar no primeiro dia do mês corrente, por convenção)
    - **fred-md, ppi, ea-md & ea-qd:** Primeiro dia do mês
    - **epu & unemployment:** Desconhecido, é importante que se verifique e confirme a informação (acredito que seja o último, mas por convenção deverá ficar mesmo o primeiro dia)

In [18]:
df_target['Date'] = df_target.Date.dt.to_period("M").dt.to_timestamp()

In [19]:
df_target.head()

        Date  Valor
0 1949-01-01    4.4
1 1949-02-01    4.2
2 1949-03-01    4.8
3 1949-04-01    3.8
4 1949-05-01    4.5

In [20]:
df_exchange['Date'] = df_exchange.Date.dt.to_period("M").dt.to_timestamp()

In [21]:
df_exchange.head()

        Date   Valor
0 1999-01-01  1.1384
1 1999-02-01  1.1018
2 1999-03-01  1.0742
3 1999-04-01  1.0597
4 1999-05-01  1.0456

In [22]:
dfs = {
    'target': df_target, 'fred-md': df_fred_md,
    'ea-md': df_ea_md, 'ea-qd': df_ea_qd,
    'epu': df_epu, 'unemployment': df_unemployment,
    'exchange': df_exchange, 'ppi': df_ppi
}

for df_name, df in dfs.items():
    print(f"Data mínima de {df_name} é `{df['Date'].min()}`")

Data mínima de target é `1949-01-01 00:00:00`
Data mínima de fred-md é `1959-01-01 00:00:00`
Data mínima de ea-md é `2000-01-01 00:00:00`
Data mínima de ea-qd é `2000-01-01 00:00:00`
Data mínima de epu é `1998-01-01 00:00:00`
Data mínima de unemployment é `1983-01-01 00:00:00`
Data mínima de exchange é `1999-01-01 00:00:00`
Data mínima de ppi é `2000-01-01 00:00:00`

In [23]:
for df_name, df in dfs.items():
    print(f"Data máxima de {df_name} é `{df['Date'].max()}`")

Data máxima de target é `2025-12-01 00:00:00`
Data máxima de fred-md é `2025-12-01 00:00:00`
Data máxima de ea-md é `2026-02-01 00:00:00`
Data máxima de ea-qd é `2026-02-01 00:00:00`
Data máxima de epu é `2025-10-01 00:00:00`
Data máxima de unemployment é `2025-12-01 00:00:00`
Data máxima de exchange é `2026-02-01 00:00:00`
Data máxima de ppi é `2026-03-01 00:00:00`

In [24]:
for df_name, df in dfs.items():
    print("-" * 30)
    print(f"Columns for {df_name} dataset")
    print("-" * 30)
    for col in df.columns:
        print(f"# {col}")

------------------------------
Columns for target dataset
------------------------------
# Date
# Valor
------------------------------
Columns for fred-md dataset
------------------------------
# Date
# INDPRO
# IPFINAL
# IPCONGD
# AWOTMAN
# AWHMAN
# FEDFUNDS
# GS1
# GS5
# GS10
# AAA
# BAA
# OILPRICEx
# CUSR0000SAC
# PCEPI
# S&P 500
------------------------------
Columns for ea-md dataset
------------------------------
# Date
# UNETOT_PT
# UNEO25_PT
# UNEU25_PT
# REER42_PT
# LTIRT_PT
# IPMN_PT
# IPCAG_PT
# IPCOG_PT
# IPDCOG_PT
# IPNDCOG_PT
# IPING_PT
# IPNRG_PT
# TRNMN_PT
# TRNCAG_PT
# TRNCOG_PT
# TRNDCOG_PT
# TRNNDCOG_PT
# TRNING_PT
# TRNNRG_PT
# HICPOV_PT
# HICPNEF_PT
# HICPG_PT
# HICPIN_PT
# HICPSV_PT
# HICPNG_PT
# ICONFIX_PT
# CCONFIX_PT
# ESENTIX_PT
# KCONFIX_PT
# RTCONFIX_PT
# SCONFIX_PT
# BCI_PT
# CCI_PT
# SHIX_PT
------------------------------
Columns for ea-qd dataset
------------------------------
# Date
# GDP_PT
# EXPGS_PT
# IMPGS_PT
# GFCE_PT
# HFCE_PT
# CONSD_PT
# GCF_PT
# GFCF_PT
# GFACON_PT
# GFAMG_PT
# GNFCPS_PT
# GNFCIR_PT
# GHIR_PT
# GHSR_PT
# TEMP_PT
# EMP_PT
# SEMP_PT
# THOURS_PT
# EMPAG_PT
# EMPIN_PT
# EMPMN_PT
# EMPCON_PT
# EMPRT_PT
# EMPIT_PT
# EMPFC_PT
# EMPRE_PT
# EMPPR_PT
# EMPPA_PT
# EMPENT_PT
# RPRP_PT
# WS_PT
# ESC_PT
# TASS.SDB_PT
# TASS.LBD_PT
# TASS.SLN_PT
# TASS.LLN_PT
# TLB.SDB_PT
# TLB.LBD_PT
# TLB.SLN_PT
# TLB.LLN_PT
# NFCASS_PT
# NFCASS.SLN_PT
# NFCASS.LLN_PT
# NFCLB_PT
# NFCLB.SLN_PT
# NFCLB.LLN_PT
# GGASS_PT
# GGASS.LLN_PT
# GGLB_PT
# GGLB.SLN_PT
# GGLB.LLN_PT
# HHASS_PT
# HHASS.LLN_PT
# HHLB_PT
# HHLB.SLN_PT
# HHLB.LLN_PT
# ULCIN_PT
# ULCMQ_PT
# ULCMN_PT
# ULCCON_PT
# ULCRT_PT
# ULCFC_PT
# ULCRE_PT
# ULCPR_PT
# DFGDP_PT
------------------------------
Columns for epu dataset
------------------------------
# Date
# epu_pt
------------------------------
Columns for unemployment dataset
------------------------------
# Date
# Value
------------------------------
Columns for exchange dataset
------------------------------
# Date
# Valor
------------------------------
Columns for ppi dataset
------------------------------
# Date
# PPIPT

In [25]:
df_target.rename({'Valor': 'inflation'}, axis=1, inplace=True)
df_unemployment.rename({'Value': 'unemployment_up_15'}, axis=1, inplace=True)
df_exchange.rename({'Valor': 'exchange'}, axis=1, inplace=True)

In [26]:
for df_name, df in dfs.items():
    rename = dict()
    for col in df.columns[1:]:
        rename[col] = f'{col}_{df_name}'
    df.rename(rename, axis=1, inplace=True)

In [27]:
total = 0
for df_name, df in dfs.items():
    print(f"{df_name} dataset: {df.shape[1] - 1} colunas")
    total += df.shape[1] - 1 # Eliminar data

print("=" * 30)
print(f"Total: {total} colunas")

target dataset: 1 colunas
fred-md dataset: 15 colunas
ea-md dataset: 34 colunas
ea-qd dataset: 65 colunas
epu dataset: 1 colunas
unemployment dataset: 1 colunas
exchange dataset: 1 colunas
ppi dataset: 1 colunas
==============================
Total: 119 colunas

In [28]:
for df_name, df in dfs.items():
    print("-" * 30)
    print(f"Columns for {df_name} dataset")
    print("-" * 30)
    for col in df.columns:
        print(f"# {col}")

------------------------------
Columns for target dataset
------------------------------
# Date
# inflation_target
------------------------------
Columns for fred-md dataset
------------------------------
# Date
# INDPRO_fred-md
# IPFINAL_fred-md
# IPCONGD_fred-md
# AWOTMAN_fred-md
# AWHMAN_fred-md
# FEDFUNDS_fred-md
# GS1_fred-md
# GS5_fred-md
# GS10_fred-md
# AAA_fred-md
# BAA_fred-md
# OILPRICEx_fred-md
# CUSR0000SAC_fred-md
# PCEPI_fred-md
# S&P 500_fred-md
------------------------------
Columns for ea-md dataset
------------------------------
# Date
# UNETOT_PT_ea-md
# UNEO25_PT_ea-md
# UNEU25_PT_ea-md
# REER42_PT_ea-md
# LTIRT_PT_ea-md
# IPMN_PT_ea-md
# IPCAG_PT_ea-md
# IPCOG_PT_ea-md
# IPDCOG_PT_ea-md
# IPNDCOG_PT_ea-md
# IPING_PT_ea-md
# IPNRG_PT_ea-md
# TRNMN_PT_ea-md
# TRNCAG_PT_ea-md
# TRNCOG_PT_ea-md
# TRNDCOG_PT_ea-md
# TRNNDCOG_PT_ea-md
# TRNING_PT_ea-md
# TRNNRG_PT_ea-md
# HICPOV_PT_ea-md
# HICPNEF_PT_ea-md
# HICPG_PT_ea-md
# HICPIN_PT_ea-md
# HICPSV_PT_ea-md
# HICPNG_PT_ea-md
# ICONFIX_PT_ea-md
# CCONFIX_PT_ea-md
# ESENTIX_PT_ea-md
# KCONFIX_PT_ea-md
# RTCONFIX_PT_ea-md
# SCONFIX_PT_ea-md
# BCI_PT_ea-md
# CCI_PT_ea-md
# SHIX_PT_ea-md
------------------------------
Columns for ea-qd dataset
------------------------------
# Date
# GDP_PT_ea-qd
# EXPGS_PT_ea-qd
# IMPGS_PT_ea-qd
# GFCE_PT_ea-qd
# HFCE_PT_ea-qd
# CONSD_PT_ea-qd
# GCF_PT_ea-qd
# GFCF_PT_ea-qd
# GFACON_PT_ea-qd
# GFAMG_PT_ea-qd
# GNFCPS_PT_ea-qd
# GNFCIR_PT_ea-qd
# GHIR_PT_ea-qd
# GHSR_PT_ea-qd
# TEMP_PT_ea-qd
# EMP_PT_ea-qd
# SEMP_PT_ea-qd
# THOURS_PT_ea-qd
# EMPAG_PT_ea-qd
# EMPIN_PT_ea-qd
# EMPMN_PT_ea-qd
# EMPCON_PT_ea-qd
# EMPRT_PT_ea-qd
# EMPIT_PT_ea-qd
# EMPFC_PT_ea-qd
# EMPRE_PT_ea-qd
# EMPPR_PT_ea-qd
# EMPPA_PT_ea-qd
# EMPENT_PT_ea-qd
# RPRP_PT_ea-qd
# WS_PT_ea-qd
# ESC_PT_ea-qd
# TASS.SDB_PT_ea-qd
# TASS.LBD_PT_ea-qd
# TASS.SLN_PT_ea-qd
# TASS.LLN_PT_ea-qd
# TLB.SDB_PT_ea-qd
# TLB.LBD_PT_ea-qd
# TLB.SLN_PT_ea-qd
# TLB.LLN_PT_ea-qd
# NFCASS_PT_ea-qd
# NFCASS.SLN_PT_ea-qd
# NFCASS.LLN_PT_ea-qd
# NFCLB_PT_ea-qd
# NFCLB.SLN_PT_ea-qd
# NFCLB.LLN_PT_ea-qd
# GGASS_PT_ea-qd
# GGASS.LLN_PT_ea-qd
# GGLB_PT_ea-qd
# GGLB.SLN_PT_ea-qd
# GGLB.LLN_PT_ea-qd
# HHASS_PT_ea-qd
# HHASS.LLN_PT_ea-qd
# HHLB_PT_ea-qd
# HHLB.SLN_PT_ea-qd
# HHLB.LLN_PT_ea-qd
# ULCIN_PT_ea-qd
# ULCMQ_PT_ea-qd
# ULCMN_PT_ea-qd
# ULCCON_PT_ea-qd
# ULCRT_PT_ea-qd
# ULCFC_PT_ea-qd
# ULCRE_PT_ea-qd
# ULCPR_PT_ea-qd
# DFGDP_PT_ea-qd
------------------------------
Columns for epu dataset
------------------------------
# Date
# epu_pt_epu
------------------------------
Columns for unemployment dataset
------------------------------
# Date
# unemployment_up_15_unemployment
------------------------------
Columns for exchange dataset
------------------------------
# Date
# exchange_exchange
------------------------------
Columns for ppi dataset
------------------------------
# Date
# PPIPT_ppi

In [30]:
df = pd.merge(df_ea_md, df_ea_qd, 'left', 'Date')
df = pd.merge(df, df_fred_md, 'left', 'Date')
df = pd.merge(df, df_epu, 'left', 'Date')
df = pd.merge(df, df_unemployment, 'left', 'Date')
df = pd.merge(df, df_exchange, 'left', 'Date')
df = pd.merge(df, df_ppi, 'left', 'Date')
df = pd.merge(df, df_target, 'left', 'Date')
df.head()

,Date,UNETOT_PT_ea-md,UNEO25_PT_ea-md,UNEU25_PT_ea-md,REER42_PT_ea-md,LTIRT_PT_ea-md,IPMN_PT_ea-md,IPCAG_PT_ea-md,IPCOG_PT_ea-md,IPDCOG_PT_ea-md,...,BAA_fred-md,OILPRICEx_fred-md,CUSR0000SAC_fred-md,PCEPI_fred-md,S&P 500_fred-md,epu_pt_epu,unemployment_up_15_unemployment,exchange_exchange,PPIPT_ppi,inflation_target
0,2000-01-01,5.6,4.4,12.7,96.14621,5.81,123.5,191.3,118.0,129.6,...,8.33,27.18,146.7,72.961,1425.59,107.096201,5.6,0.9791,21.5,2.1
1,2000-02-01,5.4,4.1,13.0,95.12462,5.78,122.7,177.4,119.8,131.1,...,8.29,29.35,147.6,73.191,1388.87,105.539878,5.4,0.9714,21.9,1.8
2,2000-03-01,5.3,4.0,12.4,94.49293,5.61,116.5,164.6,116.5,124.8,...,8.37,29.89,149.1,73.505,1442.21,68.844150,5.3,0.9553,21.2,1.5
3,2000-04-01,5.2,3.9,12.8,94.90064,5.52,115.5,159.3,118.0,125.3,...,8.40,25.74,148.5,73.444,1461.36,70.292778,5.2,0.9085,20.0,2.1
4,2000-05-01,5.3,4.0,13.1,94.96760,5.68,120.8,171.0,121.0,127.9,...,8.90,28.78,148.5,73.505,1418.48,78.451666,5.3,0.9303,17.9,2.5

In [31]:
print(f"Data mínima  é `{df['Date'].min()}`")
print(f"Data máxima é `{df['Date'].max()}`")

Data mínima  é `2000-01-01 00:00:00`
Data máxima é `2026-02-01 00:00:00`

In [33]:
df = df.loc[df.Date <= '2025-10-01']

In [34]:
df.shape

(310, 120)

In [35]:
print(f"Data mínima  é `{df['Date'].min()}`")
print(f"Data máxima é `{df['Date'].max()}`")

Data mínima  é `2000-01-01 00:00:00`
Data máxima é `2025-10-01 00:00:00`

In [36]:
df['OILPRICEx_fred-md_Eur'] = df['OILPRICEx_fred-md'] / df['exchange_exchange']

In [37]:
df.to_csv('dados/CompactedData.csv', index=False)